### ISSUE TITLE
Cargo taurpaulin coverage fails (sometimes) in the ci

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#201]
Last time with this error:

```
thread 'materializer::service::tests::materialize_complex_documents::case_2' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidOperationId(InvalidLength(0, 34))', aquadoggo/src/db/stores/document.rs:247:18
thread 'materializer::service::tests::materialize_complex_documents::case_2' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(11741), ...)', aquadoggo/src/db/stores/test_utils.rs:294:20
```

All the test runners pass ok.

**Comment by sandreae** [comment]
Failed on a re-run with this different error:

```
thread 'materializer::service::tests::materialize_update_document' panicked at 'Failed removing completed task from database: Transaction("attempted to acquire a connection on a closed pool")', aquadoggo/src/materializer/service.rs:63:26
thread 'materializer::service::tests::materialize_update_document' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(12623), ...)', aquadoggo/src/db/stores/test_utils.rs:294:20
failures:
    materializer::service::tests::materialize_complex_documents::case_1
    materializer::service::tests::materialize_update_document
test result: FAILED. 127 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 117.79s
```

**Comment by adzialocha** [comment]
It could be interesting to find out on what machines the gh actions run and see if we have issues with async on them?

**Comment by cafca** [comment]
THIS would be a great case for debug logs :D

**Comment by cafca** [comment]
I seem to also have this on my computer so it's not limited to the GH CI.
