### ISSUE TITLE
codecov fails in ci: `Error: certificate has expired`

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#211]
```
==> linux OS detected
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:7[11](https://github.com/p2panda/aquadoggo/runs/7435516933?check_suite_focus=true#step:6:12):[12](https://github.com/p2panda/aquadoggo/runs/7435516933?check_suite_focus=true#step:6:13))
```

**Comment by adzialocha** [comment]
Huh, just got a newsletter from codecov about some updates, sounds a little bit like its related to that? Doesn't look like a problem on our end ..

**Comment by adzialocha** [comment]
https://github.com/alan-turing-institute/sktime/issues/3057 :rofl:
