### ISSUE TITLE
Race conditions with failing tests

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#247]
I receive random failing tests when I run `cargo test` for the first times (very much looking like race conditions) :cry: - at one point they all pass ..

1. First run

```
---- db::stores::entry::tests::paginated_log_entries::case_2 stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::paginated_log_entries::case_2' panicked at 'Send to store: Custom("Entry's claimed seq num of 1 does not match expected seq num of 4 for given author and log")', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/103a133/p2panda-rs/src/test_utils/db/test_db.rs:250:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2. Second run

```
---- db::stores::entry::tests::get_lipmaa_link_entries stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::get_lipmaa_link_entries' panicked at 'Send to store: InsertionError(OperationId(Hash("0020936c7abffc9a92f7e12d5a4e4b4b0bd1bbfcdfa3440aba43ba15224fd07bcd6b")))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/103a133/p2panda-rs/src/test_utils/db/test_db.rs:250:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

3. Third run

```
---- graphql::client::dynamic_query::test::single_query stdout ----
-------------- TEST START --------------
thread 'graphql::client::dynamic_query::test::single_query' panicked at 'assertion failed: `(left == right)`
  left: `Null`,
 right: `Object({Name("byViewId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})}), Name("byDocumentId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})})})`: [
    ServerError {
        message: "Unknown field \"schema_name_0020e97f9999c4d8ab054d3dd4d0c1d8e4c7063cc06706594d69828dfae5fd22d6e9\" on type \"QueryRoot\".",
        locations: [
            Pos(2:17),
        ],
        path: [],
        extensions: None,
    },
    ServerError {
        message: "Unknown field \"schema_name_0020e97f9999c4d8ab054d3dd4d0c1d8e4c7063cc06706594d69828dfae5fd22d6e9\" on type \"QueryRoot\".",
        locations: [
            Pos(5:17),
        ],
        path: [],
        extensions: None,
    },
]', aquadoggo/src/graphql/client/dynamic_query.rs:440:13
```

4. They pass :laughing: 

---

If I remove my `target` folder and compile again I get more ..

```
---- db::stores::entry::tests::paginated_log_entries::case_6 stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::paginated_log_entries::case_6' panicked at 'Send to store: InsertionError(OperationId(Hash("00203c56166a80316aec6b629814ffbafb6bf54d9e30093e122b3cb0f7220e82f15d")))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/103a133/p2panda-rs/src/test_utils/db/test_db.rs:250:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by adzialocha** [comment]
Also:

```
failures:

---- graphql::client::dynamic_types::tests::application_schema_fields_type stdout ----
-------------- TEST START --------------
thread 'graphql::client::dynamic_types::tests::application_schema_fields_type' panicked at 'assertion failed: `(left == right)`
  left: `Object({Name("schemaFields"): Null})`,
 right: `Object({Name("schemaFields"): Object({Name("description"): String("Data fields available on documents of this schema."), Name("fields"): List([Object({Name("name"): String("bool_field"), Name("type"): Object({Name("kind"): String("SCALAR"), Name("name"): String("Boolean")})}), Object({Name("name"): String("list_field"), Name("type"): Object({Name("kind"): String("LIST"), Name("name"): Null})}), Object({Name("name"): String("relation_field"), Name("type"): Object({Name("kind"): String("OBJECT"), Name("name"): String("schema_definition_v1")})})])})})`:
[]
', aquadoggo/src/graphql/client/dynamic_types/tests.rs:218:9
```

**Comment by sandreae** [comment]
Also:

```
---- materializer::service::tests::materialize_update_document stdout ----
-------------- TEST START --------------
thread 'materializer::service::tests::materialize_update_document' panicked at 'assertion failed: `(left == right)`
  left: `DocumentViewId([OperationId(Hash("0020ba2ca68d5a78fd0ba2b09a9e622a86b5fb91ab2a47db9ff2d1de4d41aa4bcd8f"))])`,
 right: `DocumentViewId([OperationId(Hash("0020d59fb45a885be272b483dbaf6aac976c65c64d76299365c7d42421d983c86334"))])`', aquadoggo/src/materializer/service.rs:385:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'materializer::service::tests::materialize_update_document' panicked at 'Failed removing completed task from database: Transaction("attempted to acquire a connection on a closed pool")', aquadoggo/src/materializer/service.rs:64:26
```

**Comment by sandreae** [comment]
Got a real bonus run just now:

```
failures:

---- graphql::client::dynamic_query::test::collection_query stdout ----
-------------- TEST START --------------
thread 'graphql::client::dynamic_query::test::collection_query' panicked at 'assertion failed: `(left == right)`
  left: `Null`,
 right: `Object({Name("collection"): List([Object({Name("fields"): Object({Name("bool"): Boolean(true)})})])})`: [
    ServerError {
        message: "Unknown field \"all_schema_name_00203591f9ff53c0ba94e111c0bf683a761010e8d388cc1c9b82c04cd01558c55f72\" on type \"QueryRoot\".",
        locations: [
            Pos(2:17),
        ],
        path: [],
        extensions: None,
    },
]', aquadoggo/src/graphql/client/dynamic_query.rs:600:13

---- graphql::client::dynamic_query::test::type_name stdout ----
-------------- TEST START --------------
thread 'graphql::client::dynamic_query::test::type_name' panicked at 'assertion failed: `(left == right)`
  left: `Null`,
 right: `Object({Name("single"): Object({Name("__typename"): String("schema_name_0020ba2d3c7a90ca716946577cfecab5a0b91edaeaf3972396d9176ae20315413dfe"), Name("meta"): Object({Name("__typename"): String("DocumentMeta")}), Name("fields"): Object({Name("__typename"): String("schema_name_0020ba2d3c7a90ca716946577cfecab5a0b91edaeaf3972396d9176ae20315413dfeFields")})}), Name("collection"): List([Object({Name("__typename"): String("schema_name_0020ba2d3c7a90ca716946577cfecab5a0b91edaeaf3972396d9176ae20315413dfe")})])})`: [
    ServerError {
        message: "Unknown field \"schema_name_0020ba2d3c7a90ca716946577cfecab5a0b91edaeaf3972396d9176ae20315413dfe\" on type \"QueryRoot\".",
        locations: [
            Pos(2:17),
        ],
        path: [],
        extensions: None,
    },
    ServerError {
        message: "Unknown field \"all_schema_name_0020ba2d3c7a90ca716946577cfecab5a0b91edaeaf3972396d9176ae20315413dfe\" on type \"QueryRoot\".",
        locations: [
            Pos(7:17),
        ],
        path: [],
        extensions: None,
    },
]', aquadoggo/src/graphql/client/dynamic_query.rs:666:13

---- graphql::replication::query::tests::entry_by_hash stdout ----
-------------- TEST START --------------
thread 'graphql::replication::query::tests::entry_by_hash' panicked at 'Send to store: Custom("Unexpected number of inserts occured for entry with id: 00203c56166a80316aec6b629814ffbafb6bf54d9e30093e122b3cb0f7220e82f15d")', /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/p2panda-rs-0.6.0/src/test_utils/db/test_db.rs:246:26

---- materializer::tasks::dependency::tests::dispatches_reduce_tasks_for_pinned_child_dependencies::case_2 stdout ----
-------------- TEST START --------------
thread 'materializer::tasks::dependency::tests::dispatches_reduce_tasks_for_pinned_child_dependencies::case_2' panicked at 'called `Result::unwrap()` on an `Err` value: Failure("00205aeab2f108c82dff99c7198c4e8239b541b4aba4f7feffe53fddc343bdb75527 was deleted while processing task")', aquadoggo/src/materializer/tasks/dependency.rs:363:22

failures:
    graphql::client::dynamic_query::test::collection_query
    graphql::client::dynamic_query::test::type_name
    graphql::replication::query::tests::entry_by_hash
    materializer::tasks::dependency::tests::dispatches_reduce_tasks_for_pinned_child_dependencies::case_2
```

**Comment by sandreae** [comment]
Ok, interesting. Logging seems to show the `Store` and `SchemaProvider` have the expected schema, but the GraphQL schema is still wrong.

```
[2022-11-28T14:53:34Z DEBUG aquadoggo::graphql::schema] SCHEMA FROM PROVIDER
[2022-11-28T14:53:34Z DEBUG aquadoggo::graphql::schema] [
        Schema {
            id: SchemaDefinition(
                1,
            ),
            description: "Publish data schemas for your application.",
            fields: {
                "description": String,
                "fields": PinnedRelationList(
                    SchemaFieldDefinition(
                        1,
                    ),
                ),
                "name": String,
            },
        },
        Schema {
            id: SchemaFieldDefinition(
                1,
            ),
            description: "Define fields for application data schemas.",
            fields: {
                "name": String,
                "type": String,
            },
        },
        Schema {
            id: Application(
                "schema_name",
                DocumentViewId(
                    [
                        OperationId(
                            Hash(
                                "002068a2a051668718f4ca01fd73ea989de7b74b5abc3b643e912413ebae6a41067c",
                            ),
                        ),
                    ],
                ),
            ),
            description: "test schema description",
            fields: {
                "bool": Boolean,
            },
        },
        Schema {
            id: Application(
                "doggo_schema",
                DocumentViewId(
                    [
                        OperationId(
                            Hash(
                                "0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
                            ),
                        ),
                    ],
                ),
            ),
            description: "A doggo schema for testing",
            fields: {
                "age": Integer,
                "another_relation_field": PinnedRelationList(
                    Application(
                        "doggo_schema",
                        DocumentViewId(
                            [
                                OperationId(
                                    Hash(
                                        "0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
                                    ),
                                ),
                            ],
                        ),
                    ),
                ),
                "height": Float,
                "is_admin": Boolean,
                "many_profile_pictures": RelationList(
                    Application(
                        "doggo_schema",
                        DocumentViewId(
                            [
                                OperationId(
                                    Hash(
                                        "0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
                                    ),
                                ),
                            ],
                        ),
                    ),
                ),
                "many_special_profile_pictures": PinnedRelationList(
                    Application(
                        "doggo_schema",
                        DocumentViewId(
                            [
                                OperationId(
                                    Hash(
                                        "0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
                                    ),
                                ),
                            ],
                        ),
                    ),
                ),
                "profile_picture": Relation(
                    Application(
                        "doggo_schema",
                        DocumentViewId(
                            [
                                OperationId(
                                    Hash(
                                        "0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
                                    ),
                                ),
                            ],
                        ),
                    ),
                ),
                "special_profile_picture": PinnedRelation(
                    Application(
                        "doggo_schema",
                        DocumentViewId(
                            [
                                OperationId(
                                    Hash(
                                        "0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
                                    ),
                                ),
                            ],
                        ),
                    ),
                ),
                "username": String,
            },
        },
    ]
[2022-11-28T14:53:34Z DEBUG aquadoggo::graphql::schema] SCHEMA FROM STORE
[2022-11-28T14:53:34Z DEBUG aquadoggo::graphql::schema] [
        DocumentView {
            id: DocumentViewId(
                [
                    OperationId(
                        Hash(
                            "002068a2a051668718f4ca01fd73ea989de7b74b5abc3b643e912413ebae6a41067c",
                        ),
                    ),
                ],
            ),
            fields: DocumentViewFields(
                {
                    "description": DocumentViewValue {
                        operation_id: OperationId(
                            Hash(
                                "002068a2a051668718f4ca01fd73ea989de7b74b5abc3b643e912413ebae6a41067c",
                            ),
                        ),
                        value: String(
                            "test schema description",
                        ),
                    },
                    "fields": DocumentViewValue {
                        operation_id: OperationId(
                            Hash(
                                "002068a2a051668718f4ca01fd73ea989de7b74b5abc3b643e912413ebae6a41067c",
                            ),
                        ),
                        value: PinnedRelationList(
                            PinnedRelationList(
                                [
                                    DocumentViewId(
                                        [
                                            OperationId(
                                                Hash(
                                                    "0020758ce3646d5065192ff4f54121797739ca38dda474917ba1d0f1885b3b1e3dfd",
                                                ),
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                    },
                    "name": DocumentViewValue {
                        operation_id: OperationId(
                            Hash(
                                "002068a2a051668718f4ca01fd73ea989de7b74b5abc3b643e912413ebae6a41067c",
                            ),
                        ),
                        value: String(
                            "schema_name",
                        ),
                    },
                },
            ),
        },
    ]
[2022-11-28T14:53:34Z DEBUG aquadoggo::graphql::schema] [
        [
            ...
            "all_schema_name_0020ab5a754ddbde413122ac64a40df13944cda373ee1350eb2c268cacce63d39718",
            "schema_name_0020ab5a754ddbde413122ac64a40df13944cda373ee1350eb2c268cacce63d39718",
            "schema_name_0020ab5a754ddbde413122ac64a40df13944cda373ee1350eb2c268cacce63d39718Fields",
        ],
    ]
[2022-11-28T14:53:34Z DEBUG aquadoggo::graphql::schema] Finished building initial GraphQL schema
thread 'graphql::client::dynamic_query::test::single_query' panicked at 'assertion failed: `(left == right)`
  left: `Null`,
 right: `Object({Name("byViewId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})}), Name("byDocumentId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})})})`: [
    ServerError {
        message: "Unknown field \"schema_name_002068a2a051668718f4ca01fd73ea989de7b74b5abc3b643e912413ebae6a41067c\" on type \"QueryRoot\".",
        locations: [
            Pos(2:17),
        ],
        path: [],
        extensions: None,
    },
    ServerError {
        message: "Unknown field \"schema_name_002068a2a051668718f4ca01fd73ea989de7b74b5abc3b643e912413ebae6a41067c\" on type \"QueryRoot\".",
        locations: [
            Pos(5:17),
        ],
        path: [],
        extensions: None,
    },
]', aquadoggo/src/graphql/client/dynamic_query.rs:480:13
```

**Comment by adzialocha** [comment]
Maybe something with the GraphQL manager? That's the thing rebuilding the API as soon as a new schema was registered. I'm sure that takes a bit of time ..

**Comment by sandreae** [comment]
I think I found it:

```
[2022-11-28T17:50:56Z INFO  aquadoggo::graphql::schema] Subscribing GraphQL manager to schema provider
[2022-11-28T17:50:56Z DEBUG aquadoggo::graphql::schema] SCHEMA FROM PROVIDER:
[2022-11-28T17:50:56Z DEBUG aquadoggo::graphql::schema] [
        "schema_definition_v1",
        "doggo_schema 496543",
        "schema_name 4e77cf",
        "schema_field_definition_v1",
    ]
[2022-11-28T17:50:56Z DEBUG aquadoggo::schema::static_schema_provider] SCHEMA SAVED TO STATIC SCHEMA:
[2022-11-28T17:50:56Z DEBUG aquadoggo::schema::static_schema_provider] [
        "schema_definition_v1",
        "doggo_schema 496543",
        "schema_name 4e77cf",
        "schema_field_definition_v1",
    ]
[2022-11-28T17:50:56Z DEBUG aquadoggo::schema::static_schema_provider] SCHEMA LOADED FROM STATIC SCHEMA:
[2022-11-28T17:50:56Z DEBUG aquadoggo::schema::static_schema_provider] [
        "doggo_schema 496543",
        "schema_name c55291",
        "schema_definition_v1",
        "schema_field_definition_v1",
    ]
[2022-11-28T17:50:56Z DEBUG aquadoggo::graphql::schema] SCHEMA IN GRAPHQL ROOT:
[2022-11-28T17:50:56Z DEBUG aquadoggo::graphql::schema] [
        [
            "doggo_schema_0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
            "doggo_schema_0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543Fields",
            "schema_name_0020c30cee63ac3e957a00a0b4cf9c57bf181aed083072b8c9af1ef89df572c55291Fields",
            "all_doggo_schema_0020b177ec1bf26dfb3b7010d473e6d44713b29b765b99c6e60ecbfae742de496543",
            "all_schema_name_0020c30cee63ac3e957a00a0b4cf9c57bf181aed083072b8c9af1ef89df572c55291",
            "schema_name_0020c30cee63ac3e957a00a0b4cf9c57bf181aed083072b8c9af1ef89df572c55291",
        ],
    ]
[2022-11-28T17:50:56Z DEBUG aquadoggo::graphql::schema] Finished building initial GraphQL schema
thread 'graphql::client::dynamic_query::test::single_query' panicked at 'assertion failed: `(left == right)`
  left: `Null`,
 right: `Object({Name("byViewId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})}), Name("byDocumentId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})})})`: [
    ServerError {
        message: "Unknown field \"schema_name_00203a3e1148d732c0c9714a835456de4aa752c3e39f7246e04f26213859584e77cf\" on type \"QueryRoot\".",
        locations: [
            Pos(2:17),
        ],
        path: [],
        extensions: None,
    },
    ServerError {
        message: "Unknown field \"schema_name_00203a3e1148d732c0c9714a835456de4aa752c3e39f7246e04f26213859584e77cf\" on type \"QueryRoot\".",
        locations: [
            Pos(5:17),
        ],
        path: [],
        extensions: None,
    },
]', aquadoggo/src/graphql/client/dynamic_query.rs:480:13

```

**Comment by sandreae** [comment]
It seems to be that the correct schema are passed into `save_static_schemas` but when `load_static_schemas` is called shortly after, it contains different (incorrect) schema.

**Comment by sandreae** [comment]
Ok, In think we're facing several layers of issues here.

1) `static SCHEMA_PROVIDER: Lazy<Mutex<Vec<Schema>>> = Lazy::new(|| Mutex::new(Vec::new()));`

We're using the above to allow the GraphQL schema builder access to the current schemas, in particular in `create_type_info`. This works, but when running multiple tests concurrently I _think_ `SCHEMA_PROVIDER` is being written to in one process before it is read in another. 

We take a `MutexGuard` in `save_static_schemas()` [here](https://github.com/p2panda/aquadoggo/blob/670281b8680d48dad7cb6738b7a226dbf0f5288e/aquadoggo/src/schema/static_schema_provider.rs#L48-L56)  but it is dropped  as it goes out of scope and this leaves an opening where another lock can be taken out before it's read in the same test.

2) What we want to do then is keep the lock until we read again, we can return it, keeping it alive longer, but if we keep it too long we simply block our own read, and we can't pass it on because we don't have access to the `async_graphql` methods.

3) So then maybe we need a yielding mutex like `tokio::sync::Mutex` which wakes a future when a lock is released? But we can't cos it's `async` and  `create_type_info` isn't.

4) No idea.... :cry: what should we do? Hopefully I'm missing something....

I got a lot of that from: https://fasterthanli.me/articles/a-rust-match-made-in-hell#locks
