### ISSUE TITLE
Graphql panic & playground crashes with "Type not found" for unknown reason

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#248]
Yoho! First bug from the `development` branch ;-p

Not exactly sure what's going on here, ~~to replicate run `send-to-node` but change the final `012` operation schema id to be wrongly named.~~ I'm now unable to replicate the error.... it did happen though....

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/aquadoggo`
thread 'tokio-runtime-worker' panicked at 'Type 'venue_002020da00fe6fb680537b4f46858ca5e9ceb45983401cdad8abf1477330c9ce9fdc' not found!', /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/type.rs:55:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: async_graphql::model::type::__Type::new
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/type.rs:55:29
   3: async_graphql::model::field::__Field::ty::{{closure}}::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/field.rs:41:9
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   5: async_graphql::model::field::__Field::ty::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/field.rs:14:1
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   7: <async_graphql::model::field::__Field as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/field.rs:14:1
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   9: <async_graphql::model::field::__Field as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/field.rs:14:1
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  12: async_graphql::resolver_utils::container::Fields::add_set::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:209:67
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  15: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  16: <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_maybe_done.rs:79:57
  17: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  18: <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_join_all.rs:107:19
  19: async_graphql::resolver_utils::container::resolve_container_inner::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:156:53
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  21: async_graphql::resolver_utils::container::resolve_container::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:110:45
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  23: <async_graphql::model::field::__Field as async_graphql::base::OutputType>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/field.rs:14:1
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  26: <&T as async_graphql::base::OutputType>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/base.rs:102:38
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  28: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  29: async_graphql::resolver_utils::list::resolve_list::{{closure}}::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/list.rs:51:60
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  31: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  32: <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_maybe_done.rs:79:57
  33: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  34: <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_join_all.rs:107:19
  35: async_graphql::resolver_utils::list::resolve_list::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/list.rs:57:56
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  37: async_graphql::types::external::list::vec::<impl async_graphql::base::OutputType for alloc::vec::Vec<T>>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/types/external/list/vec.rs:68:57
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  39: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  40: async_graphql::types::external::optional::<impl async_graphql::base::OutputType for core::option::Option<T>>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/types/external/optional.rs:70:57
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  42: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  43: <async_graphql::model::type::__Type as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/type.rs:65:1
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  45: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  46: async_graphql::resolver_utils::container::Fields::add_set::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:209:67
  47: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  48: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  49: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  50: <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_maybe_done.rs:79:57
  51: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  52: <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_join_all.rs:107:19
  53: async_graphql::resolver_utils::container::resolve_container_inner::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:156:53
  54: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  55: async_graphql::resolver_utils::container::resolve_container::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:110:45
  56: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  57: <async_graphql::model::type::__Type as async_graphql::base::OutputType>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/type.rs:65:1
  58: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  59: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  60: <&T as async_graphql::base::OutputType>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/base.rs:102:38
  61: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  62: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  63: async_graphql::resolver_utils::list::resolve_list::{{closure}}::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/list.rs:51:60
  64: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  65: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  66: <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_maybe_done.rs:79:57
  67: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  68: <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_join_all.rs:107:19
  69: async_graphql::resolver_utils::list::resolve_list::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/list.rs:57:56
  70: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  71: async_graphql::types::external::list::vec::<impl async_graphql::base::OutputType for alloc::vec::Vec<T>>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/types/external/list/vec.rs:68:57
  72: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  73: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  74: <async_graphql::model::schema::__Schema as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/schema.rs:21:1
  75: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  76: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  77: async_graphql::resolver_utils::container::Fields::add_set::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:209:67
  78: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  79: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  80: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  81: <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_maybe_done.rs:79:57
  82: <F as futures_core::future::TryFuture>::try_poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  83: <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_join_all.rs:107:19
  84: async_graphql::resolver_utils::container::resolve_container_inner::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:156:53
  85: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  86: async_graphql::resolver_utils::container::resolve_container::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/resolver_utils/container.rs:110:45
  87: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  88: <async_graphql::model::schema::__Schema as async_graphql::base::OutputType>::resolve::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/model/schema.rs:21:1
  89: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  90: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  91: <async_graphql::types::query_root::QueryRoot<T> as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}
             at /home/sandreae/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/types/query_root.rs:35:18
  92: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by adzialocha** [comment]
This error apparently happens when relating to an unknown schema id in a relation

**Comment by sandreae** [comment]
> This error apparently happens when relating to an unknown schema id in a relation, we should be able to reproduce this

I changed the issue title 😜

**Comment by adzialocha** [comment]
> > This error apparently happens when relating to an unknown schema id in a relation, we should be able to reproduce this
> 
> I changed the issue title 😜

Oha! You couldn't reproduce it?

**Comment by sandreae** [comment]
Nope, not at all 🤔

**Comment by sandreae** [comment]
I'm gunna close this as I couldn't replicate the issue.
