### ISSUE TITLE
Irregular failing tests

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#270]
This test sometimes fails on my machine:

```
thread 'db::stores::entry::tests::paginated_log_entries::case_6' panicked at 'Send to store: Custom("Entry's claimed seq num of 1 does not match expected seq num of 23 for given public key and log")', /home/adz/.cargo/registry/src/github.com-1ecc6299db9ec823/p2panda-rs-0.6.0/src/test_utils/db/test_db.rs:246:26
```

Related discussion: https://github.com/p2panda/aquadoggo/pull/266

**Comment by adzialocha** [comment]
.. actually another whole bunch of other tests as well:

```
---- db::stores::entry::tests::paginated_log_entries::case_5 stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::paginated_log_entries::case_5' panicked at 'Send to store: EntryStoreError(Custom("Unexpected number of inserts occured for entry with id: 00201701fc74b4469c6b35e0534bf9a3f18c7c0916c9ae345cf77211572c4f035935"))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::entry::tests::paginated_log_entries::case_5

---- db::stores::entry::tests::paginated_log_entries::case_7 stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::paginated_log_entries::case_7' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchNext(0, 1))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::entry::tests::paginated_log_entries::case_7

---- graphql::client::dynamic_query::test::single_query stdout ----
-------------- TEST START --------------
thread 'graphql::client::dynamic_query::test::single_query' panicked at 'assertion failed: `(left == right)`
  left: `Null`,
 right: `Object({Name("byViewId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})}), Name("byDocumentId"): Object({Name("fields"): Object({Name("bool"): Boolean(true)})})})`: [
    ServerError {
        message: "Unknown field \"schema_name_0020a11e93df5645457a2ac457f13b5aa72731f8db6f2c51a7fe33891a6932c00d10\" on type \"QueryRoot\".",
        locations: [
            Pos(2:17),
        ],
        path: [],
        extensions: None,
    },
    ServerError {
        message: "Unknown field \"schema_name_0020a11e93df5645457a2ac457f13b5aa72731f8db6f2c51a7fe33891a6932c00d10\" on type \"QueryRoot\".",
        locations: [
            Pos(5:17),
        ],
        path: [],
        extensions: None,
    },
]', aquadoggo/src/graphql/client/dynamic_query.rs:502:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    graphql::client::dynamic_query::test::single_query

---- db::stores::document::tests::get_documents_by_schema_deleted_document stdout ----
-------------- TEST START --------------
thread 'db::stores::document::tests::get_documents_by_schema_deleted_document' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchNext(0, 1))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::document::tests::get_documents_by_schema_deleted_document

---- db::stores::document::tests::updates_a_document stdout ----
-------------- TEST START --------------
thread 'db::stores::document::tests::updates_a_document' panicked at 'Unwrap document', aquadoggo/src/db/stores/document.rs:881:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::document::tests::updates_a_document

---- db::stores::schema::tests::get_all_schema stdout ----
-------------- TEST START --------------
thread 'db::stores::schema::tests::get_all_schema' panicked at 'Failed adding schema to provider.', aquadoggo/src/test_utils/node.rs:236:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::schema::tests::get_all_schema

---- db::stores::entry::tests::paginated_log_entries::case_2 stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::paginated_log_entries::case_2' panicked at 'Send to store: OperationStoreError(InsertionError(OperationId(Hash("0020fb515d98ef19b0998c4f8cab9eac9b7515ad5f90b4c96ee35c0d7938a61a206b"))))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::entry::tests::paginated_log_entries::case_2

---- db::stores::entry::tests::paginated_log_entries::case_5 stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::paginated_log_entries::case_5' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchNext(0, 1))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::entry::tests::paginated_log_entries::case_5

---- db::stores::entry::tests::get_lipmaa_link_entries stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::get_lipmaa_link_entries' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchNext(0, 1))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::entry::tests::get_lipmaa_link_entries

---- db::stores::document::tests::gets_documents_by_schema stdout ----
-------------- TEST START --------------
thread 'db::stores::document::tests::gets_documents_by_schema' panicked at 'Send to store: ValidationError(SeqNumDoesNotMatch(1, 3))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::document::tests::gets_documents_by_schema

---- db::stores::document::tests::updates_a_document stdout ----
-------------- TEST START --------------
thread 'db::stores::document::tests::updates_a_document' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchNext(0, 1))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::document::tests::updates_a_document

---- db::stores::entry::tests::get_entry stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::get_entry' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchExisting(1, 0))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    db::stores::entry::tests::get_entry

---- db::stores::document::tests::get_documents_by_schema_deleted_document stdout ----
-------------- TEST START --------------
thread 'db::stores::document::tests::get_documents_by_schema_deleted_document' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchExisting(1, 0))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- db::stores::entry::tests::paginated_log_entries::case_1 stdout ----
-------------- TEST START --------------
thread 'db::stores::entry::tests::paginated_log_entries::case_1' panicked at 'Send to store: ValidationError(LogIdDoesNotMatchExisting(1, 0))', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/d7beb86/p2panda-rs/src/test_utils/memory_store/helpers.rs:134:26


failures:
    db::stores::document::tests::get_documents_by_schema_deleted_document
    db::stores::entry::tests::paginated_log_entries::case_1
```
